---
# Variables para grupo macos_test (macOS Mojave)

# Configuración de usuario
default_user: "admin"
lab_user: "testuser"
shared_folder: "/Users/Shared/lab_shared"

# Configuración IPv6
ipv6_enabled: true
ipv6_config_method: "static"
ipv6_address: "{{ ipv6_prefix }}::102/64"
ipv6_gateway: "{{ ipv6_prefix }}::1"

# Fallback IPv4 (VirtualBox Host-Only)
ipv4_enabled: true
ipv4_address: "192.168.56.12/24"
ipv4_gateway: "192.168.56.1"

# Servicios requeridos
required_services:
  - "com.openssh.sshd"

# Paquetes via Homebrew (opcional)
homebrew_packages:
  - python3
  - htop
  - vim
  - curl
  - wget

# Configuración de monitoreo
monitoring_enabled: true
log_directory: "/var/log/ansible_monitor"
system_check_interval: 300  # 5 minutos

# Configuración SSH
ssh_enabled: true
ssh_key_type: "ed25519"
ssh_key_path: "/Users/{{ default_user }}/.ssh/id_{{ ssh_key_type }}_ansible"

# Configuración de red (macOS specific)
network_service: "Wi-Fi"  # o "Ethernet" según la configuración
network_interface: "en0"