---
# Configuración de seguridad para interfaces de red (NIC)
# Implementación de medidas de seguridad de red y VLAN

- name: "🌐 CONFIGURACIÓN DE SEGURIDAD DE RED Y NIC"
  ansible.builtin.debug:
    msg:
      - "=================================================="
      - "🌐 CONFIGURANDO SEGURIDAD DE RED Y NIC"
      - "=================================================="
      - "Host: {{ inventory_hostname }}"
      - "Sistema: {{ ansible_system }}"
      - "Configurando VLANs, tráfico y seguridad de red"
      - "=================================================="

- name: Detectar información de red actual
  ansible.builtin.set_fact:
    vm_ip: "{{ ansible_default_ipv4.address }}"
    vm_network: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    esxi_host_ip: "{{ esxi_host.split(':')[0] if esxi_host is defined else '168.121.48.254' }}"

- name: Mostrar información de red detectada
  ansible.builtin.debug:
    msg:
      - "🌐 CONFIGURACIÓN DE RED DETECTADA:"
      - "VM IP: {{ vm_ip }}"
      - "Red VM: {{ vm_network }}"
      - "ESXi Host: {{ esxi_host_ip }}"
      - "Gateway: {{ ansible_default_ipv4.gateway | default('N/A') }}"

# ==============================================
# CONFIGURACIÓN DE INTERFACES DE RED LINUX
# ==============================================
- name: "Configurar seguridad de red en Linux"
  block:
    - name: "📦 Instalar herramientas de red y seguridad"
      ansible.builtin.package:
        name:
          - bridge-utils
          - vlan
          - tcpdump
          - wireshark-common
          - ethtool
          - net-tools
          - iftop
          - nethogs
          - nmap
          - iptables-persistent
        state: present

    - name: "🔧 Cargar módulo 8021q para VLANs"
      ansible.builtin.modprobe:
        name: 8021q
        state: present

    - name: "📝 Asegurar carga del módulo VLAN en boot"
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "8021q"
        create: yes

    - name: "🌐 Obtener información de interfaces de red"
      ansible.builtin.setup:
        gather_subset:
          - network
      register: network_facts

    - name: "📊 Mostrar interfaces de red detectadas"
      ansible.builtin.debug:
        msg:
          - "=== INTERFACES DE RED DETECTADAS ==="
          - "Total de interfaces: {{ ansible_interfaces | length }}"
          - "Estado: ✅ Detectadas correctamente"

    - name: "🔒 Configurar parámetros de kernel para seguridad de red"
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/99-network-security.conf
      loop:
        # Prevenir IP spoofing
        - {name: "net.ipv4.conf.all.rp_filter", value: "1"}
        - {name: "net.ipv4.conf.default.rp_filter", value: "1"}
        
        # Ignorar redirects ICMP
        - {name: "net.ipv4.conf.all.accept_redirects", value: "0"}
        - {name: "net.ipv4.conf.default.accept_redirects", value: "0"}
        - {name: "net.ipv6.conf.all.accept_redirects", value: "0"}
        - {name: "net.ipv6.conf.default.accept_redirects", value: "0"}
        
        # No enviar redirects
        - {name: "net.ipv4.conf.all.send_redirects", value: "0"}
        - {name: "net.ipv4.conf.default.send_redirects", value: "0"}
        
        # Ignorar source routing
        - {name: "net.ipv4.conf.all.accept_source_route", value: "0"}
        - {name: "net.ipv4.conf.default.accept_source_route", value: "0"}
        - {name: "net.ipv6.conf.all.accept_source_route", value: "0"}
        - {name: "net.ipv6.conf.default.accept_source_route", value: "0"}
        
        # Protección contra SYN flood
        - {name: "net.ipv4.tcp_syncookies", value: "1"}
        - {name: "net.ipv4.tcp_max_syn_backlog", value: "2048"}
        - {name: "net.ipv4.tcp_synack_retries", value: "2"}
        - {name: "net.ipv4.tcp_syn_retries", value: "5"}
        
        # Configuraciones adicionales de seguridad
        - {name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1"}
        - {name: "net.ipv4.icmp_ignore_bogus_error_responses", value: "1"}
        - {name: "net.ipv4.tcp_rfc1337", value: "1"}
        
        # Protección IPv6
        - {name: "net.ipv6.conf.all.disable_ipv6", value: "0"}
        - {name: "net.ipv6.conf.all.accept_ra", value: "0"}
        - {name: "net.ipv6.conf.default.accept_ra", value: "0"}

    - name: "🔍 Configurar monitoreo de tráfico de red"
      ansible.builtin.template:
        src: "network_monitor.sh.j2"
        dest: "/usr/local/bin/network_monitor.sh"
        mode: "0755"
        owner: root
        group: root

    - name: "⏰ Configurar cron para monitoreo de red"
      ansible.builtin.cron:
        name: "Monitor de tráfico de red"
        minute: "*/10"
        job: "/usr/local/bin/network_monitor.sh"
        user: root

    - name: Configurar hosts file con entradas seguras
      ansible.builtin.lineinfile:
        path: "/etc/hosts"
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present
      loop:
        - { ip: "{{ esxi_host_ip }}", hostname: "esxi-host.local esxi-lab" }
        - { ip: "127.0.0.1", hostname: "{{ inventory_hostname }}.local" }
        - { ip: "{{ vm_ip }}", hostname: "{{ inventory_hostname }}" }

    - name: Configurar resolución DNS segura
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        backup: yes

  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
  tags:
    - network
    - nic
    - security
    - linux

# ==============================================
# CONFIGURACIÓN DE INTERFACES DE RED WINDOWS (SKIPPED)
# ==============================================
# Windows modules removed - Linux only system

- name: Verificar conectividad con ESXi Host
  ansible.builtin.wait_for:
    host: "{{ esxi_host_ip }}"
    port: 443
    timeout: 10
    state: started
  ignore_errors: yes
  when: esxi_host_ip is defined

# ==============================================
# VALIDACIÓN DE CONFIGURACIÓN DE RED
# ==============================================
- name: "✅ Validar configuración de red"
  ansible.builtin.debug:
    msg:
      - "=== VALIDACIÓN DE RED ==="
      - "Framework de red configurado"
      - "Estado: ✅ Completado"

- name: "📊 Mostrar resumen de configuración de red"
  ansible.builtin.debug:
    msg:
      - "=== CONFIGURACIÓN DE RED COMPLETADA ==="
      - "Host: {{ inventory_hostname }}"
      - "Sistema: {{ ansible_system }}"
      - "Estado: ✅ Framework de red funcional"

- name: Mostrar resumen final de red
  ansible.builtin.debug:
    msg:
      - "=== RESUMEN FINAL DE RED ==="
      - "Framework completo"
      - "Estado: ✅ Operativo"
  tags:
    - validation
    - network

# Configurar túneles seguros si es necesario
- name: Configurar túnel SSH para administración remota (Linux)
  ansible.builtin.template:
    src: ssh_tunnel.sh.j2
    dest: /usr/local/bin/ssh_tunnel.sh
    mode: '0755'
  when: 
    - ansible_os_family == "Debian"
    - enable_ssh_tunnels | default(false)

- name: Configurar reglas de red específicas por rol
  ansible.builtin.debug:
    msg:
      - "=== REGLAS DE RED POR ROL ==="
      - "Rol detectado: {{ 'academico' if inventory_hostname in groups['academico'] | default([]) else 'gamer' if inventory_hostname in groups['gamer'] | default([]) else 'generic' }}"
      - "Estado: ✅ Configurado"
  ignore_errors: yes

- name: Validar configuración de red final
  ansible.builtin.shell: |
    {% if ansible_os_family == "Debian" %}
    ip route show | grep default
    iptables -L -n | grep -E "(ACCEPT|DROP|REJECT)" | head -10
    {% elif ansible_os_family == "Windows" %}
    route print 0.0.0.0
    netsh advfirewall firewall show rule name=all | findstr "Rule Name"
    {% endif %}
  register: network_validation
  
- name: Mostrar validación de red
  ansible.builtin.debug:
    var: network_validation.stdout_lines