---
# Rol principal Windows
- import_tasks: users.yml
- import_tasks: services.yml
- import_tasks: jobs.yml
- import_tasks: storage.yml

- name: Crear variable con fecha/hora actual
  set_fact:
    ahora: "{{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}"

- name: Crear carpeta para logs C:\ansible_monitor
  win_file:
    path: C:\ansible_monitor
    state: directory

- name: Crear tarea programada 'Monitor-CPU'
  win_scheduled_task:
    name: "Monitor-CPU"
    description: "Registra procesos top por CPU cada 1 minuto"
    actions:
      - path: 'powershell.exe'
        arguments: '-Command "Get-Process | Sort-Object CPU -Descending | Select -First 5 | Out-File -FilePath C:\\ansible_monitor\\cpu.txt -Append"'
    triggers:
      - type: daily
        start_boundary: "{{ ahora }}"   # <--- obligatoria
        repetition:
          interval: PT1M
          duration: PT24H
    username: 'SYSTEM'
    state: present
